[build]
  publish = "."

[[headers]]
  for = "/*.apk"
  [headers.values]
    Content-Type = "application/vnd.android.package-archive"
    Content-Disposition = "attachment; filename=\"nikki-app.apk\""
